export const products = [
  {
    id: 1,
    brand: "LANCOME",
    title: "LA VIDA ES BELLA",
    subTitle: "EAU DE TOILETTE 100 ML",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: "$" + 10500,
    stock: 10,
    img: "https://juleriaque.vtexassets.com/arquivos/ids/201480/la-vie-est-belle-edp-6580834A54130DB06CB5531233526EC2.jpg?v=1773116301",
    alt: "perfume_image",
    category: "perfumes",
    sub_category: "mujer",
  },
  {
    id: 2,
    brand: "PACO RABANNE",
    title: "PHANTOM",
    subTitle: "EAU DE TOILETTE 100 ML",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: "$" + 8500,
    stock: 10,
    img: "https://juleriaque.vtexassets.com/arquivos/ids/202787-500-auto?v=1773137620&width=500&height=auto&aspect=true",
    alt: "perfume_image",
    category: "perfumes",
    sub_category: "hombre",
  },
  {
    id: 3,
    brand: "YVES SAINT LAURENT",
    title: "BLACK OPIUM",
    subTitle: "EAU DE TOILETTE 100 ML",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: "$" + 9500,
    stock: 10,
    img: "https://juleriaque.vtexassets.com/arquivos/ids/201289-500-auto?v=1773144230&width=500&height=auto&aspect=true",
    alt: "perfume_image",
    category: "perfumes",
    sub_category: "mujer",
  },
  {
    id: 4,
    brand: "CAROLINA HERRERA",
    title: "BAD BOY",
    subTitle: "EAU DE TOILETTE 100 ML",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: "$" + 17500,
    stock: 10,
    img: "https://juleriaque.vtexassets.com/arquivos/ids/202176/bad-boy-edt-BEB3ABC93246F4D4607402FEBF7F4973.jpg?v=1773120894",
    alt: "perfume_image",
    category: "perfumes",
    sub_category: "hombre",
  },
  {
    id: 5,
    brand: "GIVENCHY",
    title: "PURE COLOR ENVY LUXE EYESHADOW",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: "$" + 3000,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686761760/maquillajes_sombras3_qmnz1j.webp",
    alt: "makeup_image",
    category: "maquillajes",
    sub_category: "shadow",
  },
  {
    id: 6,
    brand: "MAYBELLINE",
    title: "FIT ME MATTE PORELESS 16H",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: "$" + 4500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686761760/maquillajes_base1_wgiza3.webp",
    alt: "makeup_image",
    category: "maquillajes",
    sub_category: "basel",
  },
  {
    id: 7,
    brand: "MAYBELLINE",
    title: "LASH SENSATIONAL SKY HIGH WTP",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: "$" + 7500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686761760/maquillajes_rimmel2_cunkcw.webp",
    alt: "makeup_image",
    category: "maquillajes",
    sub_category: "rimmel",
  },
  {
    id: 8,
    brand: "LANCOME",
    title: "LABIAL BRILLOSO",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: "$" + 3200,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686761809/maquillajes_labial2_jk4viy.webp",
    alt: "makeup_image",
    category: "maquillajes",
    sub_category: "lipstick",
  },
  {
    id: 9,
    brand: "LANCOME",
    title: "LABIAL BRILLOSO",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: "$" + 2500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686861837/meline4_e8ir6u.jpg",
    alt: "nail_image",
    category: "unias",
    sub_category: "lipstick",
  },
  {
    id: 10,
    brand: "LANCOME",
    title: "LABIAL BRILLOSO",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: "$" + 7500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686861837/acrilicas2_zqhk3i.png",
    alt: "nail _image",
    category: "unias",
    sub_category: "lipstick",
  },
  {
    id: 11,
    brand: "LANCOME",
    title: "LABIAL BRILLOSO",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: "$" + 3000,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686861837/gel3_hqb7xe.jpg",
    alt: "nail_image",
    category: "unias",
    sub_category: "lipstick",
  },
  {
    id: 12,
    brand: "LANCOME",
    title: "LABIAL BRILLOSO",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: "$" + 4500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686861837/removedor4_lyowkn.jpg",
    alt: "nail_image",
    category: "unias",
    sub_category: "lipstick",
  },
];
