export const products = [
  ///COlECCIONES
  {
    /// DOCUMENTOS
    brand: "LANCOME",
    title: "LA VIDA ES BELLA",
    subTitle: "EAU DE TOILETTE 100 ML",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: 10500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1688593472/217827-800-auto_afrnx5.jpg",
    alt: "perfume_image",
    category: "perfumes",
    sub_category: "mujer",
  },
  {
    brand: "PACO RABANNE",
    title: "PHANTOM",
    subTitle: "EAU DE TOILETTE 100 ML",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: 8500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1688593352/202787-500-auto_jn70jl.jpg",
    alt: "perfume_image",
    category: "perfumes",
    sub_category: "hombre",
  },
  {
    brand: "YVES SAINT LAURENT",
    title: "BLACK OPIUM",
    subTitle: "EAU DE TOILETTE 100 ML",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: 9500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1688593302/201289-500-auto_udz0ot.jpg",
    alt: "perfume_image",
    category: "perfumes",
    sub_category: "mujer",
  },
  {
    brand: "CAROLINA HERRERA",
    title: "BAD BOY",
    subTitle: "EAU DE TOILETTE 100 ML",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: 17500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1688593240/bad-boy-edt-BEB3ABC93246F4D4607402FEBF7F4973_vpw6p3.jpg",
    alt: "perfume_image",
    category: "perfumes",
    sub_category: "hombre",
  },
  {
    brand: "GIVENCHY",
    title: "PURE COLOR ENVY LUXE EYESHADOW",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: 3000,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686761760/maquillajes_sombras3_qmnz1j.webp",
    alt: "makeup_image",
    category: "maquillajes",
    sub_category: "shadow",
  },
  {
    brand: "MAYBELLINE",
    title: "FIT ME MATTE PORELESS 16H",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: 4500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686761760/maquillajes_base1_wgiza3.webp",
    alt: "makeup_image",
    category: "maquillajes",
    sub_category: "basel",
  },
  {
    brand: "MAYBELLINE",
    title: "LASH SENSATIONAL SKY HIGH WTP",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: 7500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686761760/maquillajes_rimmel2_cunkcw.webp",
    alt: "makeup_image",
    category: "maquillajes",
    sub_category: "rimmel",
  },
  {
    brand: "LANCOME",
    title: "LABIAL BRILLOSO",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: 3200,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686761809/maquillajes_labial2_jk4viy.webp",
    alt: "makeup_image",
    category: "maquillajes",
    sub_category: "lipstick",
  },
  {
    brand: "MELINE",
    title: "ESMALTES",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: 2500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686861837/meline4_e8ir6u.jpg",
    alt: "nail_image",
    category: "unias",
    sub_category: "esmaltes",
  },
  {
    brand: "CHERIMOYA",
    title: "ACRILICO",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: 7500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686861837/acrilicas2_zqhk3i.png",
    alt: "nail _image",
    category: "unias",
    sub_category: "lipstick",
  },
  {
    brand: "CHERIMOYA",
    title: "GEL DE CONSTRUCCION",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: 3000,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686861837/gel3_hqb7xe.jpg",
    alt: "nail_image",
    category: "unias",
    sub_category: "construccion",
  },
  {
    brand: "CHERIMOYA",
    title: "REMOVEDOR DE ESMALTE",
    subTitle: " ",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Fugiat ea, hic obcaecati, nam cupiditate eaque aliquid et voluptatum accusamus aliquam autem molestias sit perferendis, magnam ducimus nisi! Doloribus, dolores nesciunt.",
    price: 4500,
    stock: 10,
    img: "https://res.cloudinary.com/defldhv32/image/upload/v1686861837/removedor4_lyowkn.jpg",
    alt: "nail_image",
    category: "unias",
    sub_category: "removedor",
  },
];
